development:
  password: ""
  theme_id: ""
  store: ""
  ignore_files:
    - config/settings_data.json

production:
  password: ""
  theme_id: ""
  store: ""
  ignore_files:
    - config/settings_data.json
